import 'dart:typed_data';

import 'package:http/http.dart' as http;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../providers/snapshot_provider.dart';

class PdfExportService {
  static Future<Uint8List> generate(SnapshotData data) async {
    final doc = pw.Document();

    // Pre-fetch logo images
    final logoImages = <pw.MemoryImage>[];
    for (final logo in data.logos) {
      final url = logo['file_url'] as String?;
      if (url != null && url.isNotEmpty) {
        try {
          final response = await http.get(Uri.parse(url));
          if (response.statusCode == 200) {
            logoImages.add(pw.MemoryImage(response.bodyBytes));
          }
        } catch (_) {}
      }
    }

    doc.addPage(_buildCoverPage(data));
    doc.addPage(_buildColorsTypographyPage(data));

    if (logoImages.isNotEmpty) {
      doc.addPage(_buildLogosPage(logoImages));
    }

    doc.addPage(_buildVoiceAudiencePage(data));

    if (data.pillars.isNotEmpty) {
      doc.addPage(_buildPillarsPage(data));
    }

    return doc.save();
  }

  // ── Cover ─────────────────────────────────────────────────

  static pw.Page _buildCoverPage(SnapshotData data) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Center(
        child: pw.Column(
          mainAxisAlignment: pw.MainAxisAlignment.center,
          children: [
            pw.Text(
              data.brand.name,
              style: pw.TextStyle(
                fontSize: 48,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            if (data.brand.description != null) ...[
              pw.SizedBox(height: 16),
              pw.Text(
                data.brand.description!,
                style: const pw.TextStyle(
                  fontSize: 16,
                  color: PdfColors.grey600,
                ),
                textAlign: pw.TextAlign.center,
              ),
            ],
            pw.SizedBox(height: 48),
            pw.Container(
              width: 60,
              height: 4,
              color: _hexToPdfColor('#C8F135'),
            ),
            pw.SizedBox(height: 24),
            pw.Text(
              'Brand Guidelines',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey500,
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              'Generated by Beacon',
              style: const pw.TextStyle(
                fontSize: 12,
                color: PdfColors.grey400,
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Colors + Typography ───────────────────────────────────

  static pw.Page _buildColorsTypographyPage(SnapshotData data) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Brand Colors'),
          pw.SizedBox(height: 16),
          if (data.colors.isEmpty)
            pw.Text('No colors defined.', style: _mutedStyle())
          else
            pw.Wrap(
              spacing: 16,
              runSpacing: 16,
              children: data.colors.map((c) {
                final hex = c['hex'] as String? ?? '#888888';
                final label = c['label'] as String? ?? '';
                final pdfColor = _hexToPdfColor(hex);
                return pw.Column(
                  children: [
                    pw.Container(
                      width: 48,
                      height: 48,
                      decoration: pw.BoxDecoration(
                        color: pdfColor,
                        shape: pw.BoxShape.circle,
                      ),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(label,
                        style: const pw.TextStyle(fontSize: 9)),
                    pw.Text(hex,
                        style: const pw.TextStyle(
                            fontSize: 8, color: PdfColors.grey500)),
                  ],
                );
              }).toList(),
            ),
          pw.SizedBox(height: 32),
          _sectionTitle('Typography'),
          pw.SizedBox(height: 16),
          if (data.fonts.isEmpty)
            pw.Text('No fonts defined.', style: _mutedStyle())
          else
            ...data.fonts.map((f) {
              final family = f['family'] as String? ?? 'Unknown';
              final label = f['label'] as String? ?? 'Body';
              return pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 16),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text(family,
                            style: pw.TextStyle(
                                fontSize: 18,
                                fontWeight: pw.FontWeight.bold)),
                        pw.Container(
                          padding: const pw.EdgeInsets.symmetric(
                              horizontal: 8, vertical: 2),
                          decoration: pw.BoxDecoration(
                            color: PdfColors.grey200,
                            borderRadius: pw.BorderRadius.circular(4),
                          ),
                          child: pw.Text(label,
                              style: const pw.TextStyle(fontSize: 10)),
                        ),
                      ],
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      'Aa Bb Cc Dd Ee Ff Gg Hh 0123456789',
                      style: const pw.TextStyle(
                          fontSize: 14, color: PdfColors.grey500),
                    ),
                  ],
                ),
              );
            }),
        ],
      ),
    );
  }

  // ── Logos ──────────────────────────────────────────────────

  static pw.Page _buildLogosPage(List<pw.MemoryImage> images) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Logo Variations'),
          pw.SizedBox(height: 16),
          pw.Wrap(
            spacing: 16,
            runSpacing: 16,
            children: images
                .map((img) => pw.Container(
                      width: 150,
                      height: 150,
                      padding: const pw.EdgeInsets.all(12),
                      decoration: pw.BoxDecoration(
                        border:
                            pw.Border.all(color: PdfColors.grey300),
                        borderRadius: pw.BorderRadius.circular(8),
                      ),
                      child: pw.Center(
                        child: pw.Image(img, fit: pw.BoxFit.contain),
                      ),
                    ))
                .toList(),
          ),
        ],
      ),
    );
  }

  // ── Voice & Audience ──────────────────────────────────────

  static pw.Page _buildVoiceAudiencePage(SnapshotData data) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Brand Voice'),
          pw.SizedBox(height: 16),
          if (data.voice == null)
            pw.Text('No voice profile defined.', style: _mutedStyle())
          else ...[
            if (data.voice!['archetype'] != null)
              pw.Text(
                data.voice!['archetype'] as String,
                style: pw.TextStyle(
                    fontSize: 22, fontWeight: pw.FontWeight.bold),
              ),
            if (data.voice!['mission_statement'] != null) ...[
              pw.SizedBox(height: 8),
              pw.Container(
                padding: const pw.EdgeInsets.only(left: 12),
                decoration: const pw.BoxDecoration(
                  border: pw.Border(
                    left: pw.BorderSide(
                        color: PdfColor.fromInt(0xFFC8F135), width: 2),
                  ),
                ),
                child: pw.Text(
                  data.voice!['mission_statement'] as String,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontStyle: pw.FontStyle.italic,
                    color: PdfColors.grey600,
                  ),
                ),
              ),
            ],
            pw.SizedBox(height: 16),
            _toneBar('Formal',
                (data.voice!['tone_formal'] as num?)?.toInt() ?? 5),
            _toneBar('Serious',
                (data.voice!['tone_serious'] as num?)?.toInt() ?? 5),
            _toneBar('Bold',
                (data.voice!['tone_bold'] as num?)?.toInt() ?? 5),
          ],
          pw.SizedBox(height: 32),
          _sectionTitle('Target Audience'),
          pw.SizedBox(height: 16),
          if (data.audience == null)
            pw.Text('No audience profile defined.', style: _mutedStyle())
          else ...[
            if (data.audience!['persona_name'] != null)
              pw.Text(
                data.audience!['persona_name'] as String,
                style: pw.TextStyle(
                    fontSize: 18, fontWeight: pw.FontWeight.bold),
              ),
            if (data.audience!['persona_summary'] != null)
              pw.Padding(
                padding: const pw.EdgeInsets.only(top: 4),
                child: pw.Text(
                  data.audience!['persona_summary'] as String,
                  style: const pw.TextStyle(
                      fontSize: 12, color: PdfColors.grey600),
                ),
              ),
            if (data.audience!['age_range'] != null) ...[
              pw.SizedBox(height: 12),
              pw.Row(children: [
                pw.Text('Age Range: ',
                    style: pw.TextStyle(
                        fontSize: 11, fontWeight: pw.FontWeight.bold)),
                pw.Text(data.audience!['age_range'] as String,
                    style: const pw.TextStyle(fontSize: 11)),
              ]),
            ],
            if (data.audience!['interests'] != null) ...[
              pw.SizedBox(height: 8),
              pw.Text('Interests',
                  style: pw.TextStyle(
                      fontSize: 11, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text(
                (data.audience!['interests'] is List)
                    ? (data.audience!['interests'] as List).join(', ')
                    : data.audience!['interests'].toString(),
                style: const pw.TextStyle(
                    fontSize: 11, color: PdfColors.grey600),
              ),
            ],
          ],
        ],
      ),
    );
  }

  // ── Content Pillars ───────────────────────────────────────

  static pw.Page _buildPillarsPage(SnapshotData data) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Content Pillars'),
          pw.SizedBox(height: 16),
          pw.Wrap(
            spacing: 8,
            runSpacing: 8,
            children: data.pillars.map((p) {
              final name = p['name'] as String? ?? '';
              final colorHex = p['color'] as String?;
              final pdfColor = colorHex != null
                  ? _hexToPdfColor(colorHex)
                  : PdfColors.indigo;
              return pw.Container(
                padding: const pw.EdgeInsets.symmetric(
                    horizontal: 12, vertical: 6),
                decoration: pw.BoxDecoration(
                  color: pdfColor,
                  borderRadius: pw.BorderRadius.circular(999),
                ),
                child: pw.Text(
                  name,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
              );
            }).toList(),
          ),
          pw.SizedBox(height: 24),
          ...data.pillars.map((p) {
            final name = p['name'] as String? ?? '';
            final desc = p['description'] as String?;
            return pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 12),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(name,
                      style: pw.TextStyle(
                          fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  if (desc != null && desc.isNotEmpty)
                    pw.Text(desc,
                        style: const pw.TextStyle(
                            fontSize: 11, color: PdfColors.grey600)),
                ],
              ),
            );
          }),
        ],
      ),
    );
  }

  // ── Helpers ───────────────────────────────────────────────

  static pw.Widget _sectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold),
    );
  }

  static pw.TextStyle _mutedStyle() {
    return pw.TextStyle(
      fontSize: 12,
      fontStyle: pw.FontStyle.italic,
      color: PdfColors.grey500,
    );
  }

  static PdfColor _hexToPdfColor(String hex) {
    final clean = hex.replaceFirst('#', '');
    if (clean.length == 6 && RegExp(r'^[0-9A-Fa-f]{6}$').hasMatch(clean)) {
      final intVal = int.parse(clean, radix: 16);
      return PdfColor.fromInt(0xFF000000 | intVal);
    }
    return PdfColors.grey;
  }

  static pw.Widget _toneBar(String label, int value) {
    final filled = value.clamp(0, 10);
    final empty = 10 - filled;

    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 60,
            child: pw.Text(label,
                style: const pw.TextStyle(fontSize: 11)),
          ),
          if (filled > 0)
            pw.Expanded(
              flex: filled,
              child: pw.Container(
                height: 8,
                decoration: pw.BoxDecoration(
                  color: const PdfColor.fromInt(0xFFC8F135),
                  borderRadius: pw.BorderRadius.only(
                    topLeft: const pw.Radius.circular(4),
                    bottomLeft: const pw.Radius.circular(4),
                    topRight: empty == 0
                        ? const pw.Radius.circular(4)
                        : pw.Radius.zero,
                    bottomRight: empty == 0
                        ? const pw.Radius.circular(4)
                        : pw.Radius.zero,
                  ),
                ),
              ),
            ),
          if (empty > 0)
            pw.Expanded(
              flex: empty,
              child: pw.Container(
                height: 8,
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey200,
                  borderRadius: pw.BorderRadius.only(
                    topRight: const pw.Radius.circular(4),
                    bottomRight: const pw.Radius.circular(4),
                    topLeft: filled == 0
                        ? const pw.Radius.circular(4)
                        : pw.Radius.zero,
                    bottomLeft: filled == 0
                        ? const pw.Radius.circular(4)
                        : pw.Radius.zero,
                  ),
                ),
              ),
            ),
          pw.SizedBox(
            width: 24,
            child: pw.Text('$value',
                textAlign: pw.TextAlign.right,
                style: const pw.TextStyle(fontSize: 10)),
          ),
        ],
      ),
    );
  }
}
